services:
  - type: web
    name: ferramenta-web-scraping
    env: docker
    region: ohio
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
